-- ==========================================
-- GACIA ERP - FULL DATABASE SCHEMA TEMPLATE
-- ==========================================
-- This script contains the entire database structure, including tables, 
-- RLS policies, functions, and triggers.
-- 
-- INSTRUCTIONS FOR NEW INSTALLATION:
-- 1. Create a new Supabase project.
-- 2. Go to the SQL Editor and run this entire script.
-- 3. In the "Authentication" > "Users" section, create an initial user
--    with email 'admin@gmail.com' (this email is specially treated in policies).
-- 4. After the user is created, obtain their ID (UUID) and manually 
--    insert a profile record in the 'profiles' table if the trigger below 
--    doesn't handle it yet.
-- ==========================================

-- 0. CLEANUP (Optional - Use with caution)
-- DROP SCHEMA public CASCADE;
-- CREATE SCHEMA public;

-- 1. BASE TABLES & SETTINGS
CREATE TABLE IF NOT EXISTS public.settings (
    key text PRIMARY KEY,
    value text,
    updated_at timestamp with time zone DEFAULT now()
);

-- Default Settings
INSERT INTO public.settings (key, value) VALUES
('system_name', 'Gacia ERP'),
('currency', 'BOL'),
('language', 'Español'),
('theme', 'light'),
('enable_tax', 'true'),
('tax_rate', '13'),
('tax_name', 'IVA')
ON CONFLICT (key) DO NOTHING;

-- 2. BRANCHES & USERS
CREATE TABLE IF NOT EXISTS public.branches (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    address text,
    phone text,
    active boolean DEFAULT true,
    logo_url text,
    created_at timestamp with time zone DEFAULT now()
);

-- Default Branch
INSERT INTO public.branches (name, address, active) 
VALUES ('Casa Matriz', 'Dirección Central', true)
ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS public.profiles (
    id uuid REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    email text UNIQUE,
    full_name text,
    role text DEFAULT 'Empleado', -- Administrador, Empleado, Cajero
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.user_branches (
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    branch_id bigint REFERENCES public.branches(id) ON DELETE CASCADE,
    created_at timestamp with time zone DEFAULT now(),
    PRIMARY KEY (user_id, branch_id)
);

-- 3. ROLES & PERMISSIONS
CREATE TABLE IF NOT EXISTS public.roles (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    name text UNIQUE NOT NULL,
    description text,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.role_permissions (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    role_name text NOT NULL,
    menu_key text NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    UNIQUE(role_name, menu_key)
);

INSERT INTO public.roles (name, description) VALUES
('Administrador', 'Acceso total.'),
('Empleado', 'Gestión operativa.'),
('Cajero', 'Foco en ventas.')
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.role_permissions (role_name, menu_key) VALUES
('Administrador', 'dashboard'), ('Administrador', 'pos'), ('Administrador', 'sales'), ('Administrador', 'quotations'),
('Administrador', 'inventory'), ('Administrador', 'branches'), ('Administrador', 'suppliers'), ('Administrador', 'purchases'),
('Administrador', 'transfers'), ('Administrador', 'reports'), ('Administrador', 'customers'), ('Administrador', 'users'),
('Administrador', 'classifications'), ('Administrador', 'settings'),
('Empleado', 'dashboard'), ('Empleado', 'pos'), ('Empleado', 'sales'), ('Empleado', 'inventory'), 
('Empleado', 'suppliers'), ('Empleado', 'purchases'), ('Empleado', 'transfers'), ('Empleado', 'customers'),
('Cajero', 'dashboard'), ('Cajero', 'pos'), ('Cajero', 'sales'), ('Cajero', 'customers')
ON CONFLICT DO NOTHING;

-- 4. INVENTORY SYSTEM
CREATE TABLE IF NOT EXISTS public.categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.brands (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    name text NOT NULL UNIQUE,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.models (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    name text NOT NULL,
    brand_id uuid REFERENCES public.brands(id) ON DELETE CASCADE,
    created_at timestamp with time zone DEFAULT now(),
    UNIQUE(name, brand_id)
);

CREATE TABLE IF NOT EXISTS public.products (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku text UNIQUE,
    name text NOT NULL,
    description text,
    image_url text,
    category_id bigint REFERENCES public.categories(id),
    brand_id uuid REFERENCES public.brands(id),
    model_id uuid REFERENCES public.models(id),
    cost_price numeric DEFAULT 0,
    price numeric DEFAULT 0,
    stock numeric DEFAULT 0, -- Global Stock
    active boolean DEFAULT true,
    manage_batches boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.product_branch_settings (
    product_id bigint REFERENCES public.products(id) ON DELETE CASCADE,
    branch_id bigint REFERENCES public.branches(id) ON DELETE CASCADE,
    stock numeric DEFAULT 0,
    min_stock numeric DEFAULT 0,
    price numeric, -- Override global price if set
    PRIMARY KEY (product_id, branch_id)
);

-- 5. ENTITIES (CUSTOMERS & SUPPLIERS)
CREATE TABLE IF NOT EXISTS public.suppliers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    tax_id text,
    contact_name text,
    phone text,
    email text,
    address text,
    active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.customers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    tax_id text,
    email text,
    phone text,
    address text,
    active boolean DEFAULT true,
    current_balance numeric DEFAULT 0,
    credit_limit numeric DEFAULT 0,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.customer_payments (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    customer_id bigint REFERENCES public.customers(id) ON DELETE CASCADE,
    amount numeric NOT NULL,
    method text, -- Efectivo, Transferencia, etc.
    notes text,
    created_at timestamp with time zone DEFAULT now()
);

-- 6. TRANSACTIONS
-- SALES
CREATE TABLE IF NOT EXISTS public.sales (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    sale_number SERIAL,
    user_id uuid REFERENCES public.profiles(id),
    branch_id bigint REFERENCES public.branches(id),
    customer_id bigint REFERENCES public.customers(id),
    total numeric DEFAULT 0,
    subtotal numeric DEFAULT 0,
    tax numeric DEFAULT 0,
    discount numeric DEFAULT 0,
    is_credit boolean DEFAULT false,
    payment_method text DEFAULT 'Efectivo',
    status text DEFAULT 'Completada',
    can_edit boolean DEFAULT false,
    can_void boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.sale_items (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    sale_id uuid REFERENCES public.sales(id) ON DELETE CASCADE,
    product_id bigint REFERENCES public.products(id),
    quantity numeric NOT NULL,
    price numeric NOT NULL,
    total numeric NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);

-- PURCHASES
CREATE TABLE IF NOT EXISTS public.purchases (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    purchase_number SERIAL,
    supplier_id bigint REFERENCES public.suppliers(id),
    branch_id bigint REFERENCES public.branches(id),
    user_id uuid REFERENCES public.profiles(id),
    total numeric DEFAULT 0,
    status text DEFAULT 'Completada',
    can_edit boolean DEFAULT false,
    can_void boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.purchase_items (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    purchase_id uuid REFERENCES public.purchases(id) ON DELETE CASCADE,
    product_id bigint REFERENCES public.products(id),
    quantity numeric NOT NULL,
    unit_cost numeric NOT NULL,
    total numeric NOT NULL,
    is_pack boolean DEFAULT false,
    units_per_pack numeric DEFAULT 1,
    created_at timestamp with time zone DEFAULT now()
);

-- QUOTATIONS
CREATE TABLE IF NOT EXISTS public.quotations (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    quotation_number SERIAL,
    customer_id bigint REFERENCES public.customers(id),
    branch_id bigint REFERENCES public.branches(id),
    user_id uuid REFERENCES public.profiles(id),
    total numeric DEFAULT 0,
    subtotal numeric DEFAULT 0,
    tax numeric DEFAULT 0,
    discount numeric DEFAULT 0,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.quotation_items (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    quotation_id uuid REFERENCES public.quotations(id) ON DELETE CASCADE,
    product_id bigint REFERENCES public.products(id),
    quantity numeric NOT NULL,
    price numeric NOT NULL,
    total numeric NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);

-- TRANSFERS
CREATE TABLE IF NOT EXISTS public.transfers (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    transfer_number SERIAL,
    origin_branch_id bigint REFERENCES public.branches(id),
    destination_branch_id bigint REFERENCES public.branches(id),
    user_id uuid REFERENCES public.profiles(id),
    status text DEFAULT 'Completado',
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.transfer_items (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    transfer_id uuid REFERENCES public.transfers(id) ON DELETE CASCADE,
    product_id bigint REFERENCES public.products(id),
    quantity numeric NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);

-- KARDEX & MOVEMENTS
CREATE TABLE IF NOT EXISTS public.kardex (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    branch_id bigint REFERENCES public.branches(id),
    product_id bigint REFERENCES public.products(id),
    type text NOT NULL, -- VENTA, COMPRA, TRASPASO_SALIDA, TRASPASO_ENTRADA, AJUSTE
    quantity numeric NOT NULL,
    balance_after numeric,
    notes text,
    reference_id text,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.inventory_movements (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    product_id bigint REFERENCES public.products(id),
    branch_id bigint REFERENCES public.branches(id),
    type text NOT NULL, -- ENTRADA, SALIDA
    quantity numeric NOT NULL,
    reason text,
    user_id uuid REFERENCES public.profiles(id),
    created_at timestamp with time zone DEFAULT now()
);

-- STOCK ADJUSTMENTS (flujo de aprobación; ver stock_adjustments.sql)
CREATE TABLE IF NOT EXISTS public.stock_adjustments (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    folio text NOT NULL UNIQUE,
    branch_id bigint NOT NULL REFERENCES public.branches(id),
    product_id bigint NOT NULL REFERENCES public.products(id),
    adjustment_type text NOT NULL CHECK (adjustment_type IN ('INCREMENTO', 'DECREMENTO', 'RECALIBRACION')),
    reason text NOT NULL CHECK (reason IN ('CONTEO_FISICO', 'MERMA', 'DANO', 'ROBO_PERDIDA', 'VENCIMIENTO', 'ERROR_CAPTURA', 'OTRO')),
    reason_detail text,
    previous_stock numeric NOT NULL DEFAULT 0,
    counted_stock numeric CHECK (counted_stock IS NULL OR counted_stock >= 0),
    quantity_change numeric NOT NULL DEFAULT 0,
    notes text,
    status text NOT NULL DEFAULT 'PENDIENTE' CHECK (status IN ('PENDIENTE', 'APROBADO', 'RECHAZADO', 'CANCELADO')),
    requested_by uuid NOT NULL,
    requested_at timestamptz NOT NULL DEFAULT now(),
    approved_by uuid,
    approved_at timestamptz,
    rejected_by uuid,
    rejected_at timestamptz,
    rejection_reason text,
    cancelled_by uuid,
    cancelled_at timestamptz,
    kardex_id uuid REFERENCES public.kardex(id),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- SPECIAL PERMISSIONS
CREATE TABLE IF NOT EXISTS public.special_permissions (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    resource_type text NOT NULL, -- 'sale', 'purchase', 'transfer'
    resource_id uuid NOT NULL,
    action text NOT NULL, -- 'modify', 'delete'
    granted_by uuid REFERENCES auth.users(id),
    expires_at timestamp with time zone DEFAULT (now() + interval '24 hours'),
    created_at timestamp with time zone DEFAULT now()
);

-- 7. RLS POLICIES (Simplified for migration)
-- Enable RLS on all tables
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.branches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_branches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.role_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.brands ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.models ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_branch_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.suppliers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customer_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sale_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchases ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchase_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quotations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quotation_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transfers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transfer_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.kardex ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_movements ENABLE ROW LEVEL SECURITY;

-- General Policy: Read for authenticated
DO $$ 
DECLARE 
    t text;
BEGIN
    FOR t IN (SELECT tablename FROM pg_tables WHERE schemaname = 'public') LOOP
        EXECUTE format('CREATE POLICY "Permitir lectura para autenticados" ON public.%I FOR SELECT USING (auth.role() = ''authenticated'');', t);
        EXECUTE format('CREATE POLICY "Permitir gestión para Administradores" ON public.%I FOR ALL USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = ''Administrador''));', t);
    END LOOP;
END $$;

-- Specific policies for operational roles (Cajero, Empleado) can be added here.
-- Example for POS:
CREATE POLICY "Gestión operativa para autenticados" ON public.sales FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Gestión operativa ítems para autenticados" ON public.sale_items FOR ALL USING (auth.role() = 'authenticated');
-- (Extend as needed)

-- 8. FUNCTIONS & TRIGGERS
-- STOCK SYNCHRONIZATION
CREATE OR REPLACE FUNCTION public.handle_product_branch_changes()
RETURNS trigger AS $$
DECLARE
    v_new_global_stock numeric;
BEGIN
    SELECT coalesce(sum(stock), 0) INTO v_new_global_stock
    FROM public.product_branch_settings
    WHERE product_id = coalesce(new.product_id, old.product_id);

    UPDATE public.products 
    SET stock = v_new_global_stock
    WHERE id = coalesce(new.product_id, old.product_id);

    RETURN coalesce(new, old);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER trg_sync_global_stock
AFTER INSERT OR UPDATE OR DELETE ON public.product_branch_settings
FOR EACH ROW EXECUTE FUNCTION public.handle_product_branch_changes();

-- DATABASE CLEANUP FUNCTION
CREATE OR REPLACE FUNCTION public.clean_database()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_admin_id uuid;
    v_main_branch_id bigint;
BEGIN
    -- 1. Identificar registros vitales a conservar
    SELECT id INTO v_admin_id FROM public.profiles WHERE email = 'admin@gmail.com' LIMIT 1;
    SELECT id INTO v_main_branch_id FROM public.branches WHERE name = 'Casa Matriz' LIMIT 1;

    -- Si no existe Casa Matriz, tomamos la primera sucursal para no romper el sistema
    IF v_main_branch_id IS NULL THEN
        SELECT id INTO v_main_branch_id FROM public.branches ORDER BY created_at ASC, id ASC LIMIT 1;
    END IF;

    -- 2. Limpiar Tablas Operativas y de Movimientos (hijos primero)
    DELETE FROM public.customer_payments;
    DELETE FROM public.sale_items;
    DELETE FROM public.purchase_items;
    DELETE FROM public.transfer_items;
    DELETE FROM public.quotation_items;
    DELETE FROM public.kardex;
    DELETE FROM public.inventory_movements;
    DELETE FROM public.notifications;
    DELETE FROM public.sales;
    DELETE FROM public.purchases;
    DELETE FROM public.transfers;
    DELETE FROM public.quotations;
    DELETE FROM public.special_permissions;

    -- Si la tabla debt_ledger existe (según versión instalada), también se limpia
    IF EXISTS (
        SELECT 1 FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE c.relname = 'debt_ledger' AND n.nspname = 'public'
    ) THEN
        EXECUTE 'DELETE FROM public.debt_ledger';
    END IF;

    -- 3. Limpiar Catálogo e Inventario
    DELETE FROM public.product_branch_settings;
    DELETE FROM public.products;
    DELETE FROM public.models;
    DELETE FROM public.brands;
    DELETE FROM public.categories;
    DELETE FROM public.customers;
    DELETE FROM public.suppliers;

    -- 4. Limpiar Usuarios Secundarios (conservando solo admin@gmail.com)
    DELETE FROM public.user_branches WHERE user_id IS DISTINCT FROM v_admin_id;
    DELETE FROM public.profiles WHERE id IS DISTINCT FROM v_admin_id OR v_admin_id IS NULL;

    -- 5. Limpiar Sucursales Secundarias (conservando solo Casa Matriz)
    DELETE FROM public.branches WHERE id IS DISTINCT FROM v_main_branch_id OR v_main_branch_id IS NULL;

    -- Nota: 'roles', 'role_permissions' y 'settings' se conservan por diseño
    -- para mantener la estructura y configuración básica del sistema.
END;
$$;

GRANT EXECUTE ON FUNCTION public.clean_database() TO authenticated;

-- END OF SCRIPT --
